version: '3'

services:
    nodejs:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        container_name: clube_amigo_graacc_backend
        restart: always
        environment:
            - HOST=mongo
        ports:
            - '80:3000'
        depends_on: [mongo]
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27018:27017'
        # volumes:
        #     - ./data:/data/db
    frontend:
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        container_name: clube_amigo_graacc_front
        restart: always
        ports:
            - '8080:8080'
